import "bootstrap/dist/css/bootstrap.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import BootstrapJs from "./bootstrapJs";
import { store } from "@/store/store";
import ReduxProvider from "../store/reduxProvider";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <BootstrapJs />
      <body className={montserrat.className}>
        <ReduxProvider store={store}>{children}</ReduxProvider>
      </body>
    </html>
  );
}
